### ISSUE TITLE
Init error

### ISSUE THREAD

**Issue by davehodg** [jckuester/lamp-stack-for-aws#3]
I checked it out. When doing a terraform init I get:

$ ../terraform -v
Terraform v0.11.7

$ ../terraform init
Initializing modules...
- module.web
- module.db

Initializing the backend...
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: 9AA2C53527BDEA68, host id: 5FRTKdZZ7D90nqt+bw0MN1ps4wA7OCbDgJgacYqqvKxJ+P0QbZN7Yi4MVL5N39s2blcOxiR2DBI=

**Comment by jckuester** [comment]
Hmm, this is what I get:

```
$ :: /tmp/lamp-stack-for-aws/terraform ‹develop› » terraform init
Initializing modules...
- module.webserver
  Getting source "modules/webserver"
- module.database
  Getting source "modules/database"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.19.0)...
- Downloading plugin for provider "template" (1.0.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.template: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ :: /tmp/lamp-stack-for-aws/terraform ‹develop› » terraform --version
Terraform v0.11.7
+ provider.aws v1.19.0
+ provider.template v1.0.0
```

**Comment by davehodg** [comment]
I can dig deeper. Googling was no help. One suggestion of recreating keys didn't work, nor putting them in ~/.terraform.

**Comment by jckuester** [comment]
Do you have any `.terraform/` folder in the [`terraform/` directory of the project](https://github.com/cloudetc/lamp-stack-for-aws/tree/develop/terraform) that might cause the problem?

The error 

```
Initializing the backend...
Error loading state: AccessDenied: Access Denied
```

might come from Terraform trying to [initialize a backend](https://www.terraform.io/docs/commands/init.html#backend-initialization). Did you add such configuration? You might want to try `terraform init -backend=false`.

**Comment by davehodg** [comment]
Checked out again and got beyond init. Weird. Closing.
